apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-iqss          # nom du déploiement
  namespace: default
spec:
  replicas: 1             # nombre de pods à lancer
  selector:
    matchLabels:
      app: api-iqss
  template:
    metadata:
      labels:
        app: api-iqss
    spec:
      containers:
      - name: api-iqss
        image: 10.2.240.5:8080/production/api-iqss:320c6013e3019a4b45c6a51e39567b938894c6d9
        ports:
        - containerPort: 8080   # port sur lequel FastAPI écoute
        envFrom:
        - secretRef:
            name: api-iqss-secret
      imagePullSecrets:
      - name: harbor-secret     # secret pour s'authentifier à Harbor
