apiVersion: v1
kind: Service
metadata:
  name: api-iqss
spec:
  selector:
    app: api-iqss        # relie au deployment
  ports:
  - port: 80             # port externe
    targetPort: 8080     # port interne du container FastAPI
  type: NodePort         # expose l'app sur un port du n≈ìud
