apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-iqss          # nom du déploiement
  namespace: uat
spec:
  replicas: 1             # nombre de pods à lancer
  selector:
    matchLabels:
      app: api-iqss
  template:
    metadata:
      labels:
        app: api-iqss
    spec:
      containers:
      - name: api-iqss
        image: 10.2.240.5:8080/production/api-iqss:uat-latest  # image depuis Harbor
        ports:
        - containerPort: 8080   # port sur lequel FastAPI écoute
        envFrom:
            - secretRef:
                name: api-iqss-secret
      imagePullSecrets:
      - name: harbor-secret     # secret pour s'authentifier à Harbor
